name=Perilla
version=0.1.0
author=piruetasxyz
maintainer=piruetasxyz
sentence=Biblioteca para leer perillas (potenciometros) con microcontroladores.
paragraph=Lee una entrada analoga y mapea su valor a otro rango. Compatible con placas Arduino y Raspberry Pi Pico.
category=Sensors
url=https://github.com/piruetasxyz/Perilla
architectures=*
includes=Perilla.h